### ISSUE TITLE
Add cookie to save wage

### ISSUE THREAD

**Issue by tomclaessens** [tomclaessens/aankoopcalc#1]
Add a cookie to save the wage input so it's less of a hassle to complete the form next time.
Unchecking the checkbox removes the existing value!

## Tasks
- [x] add checkbox to save wage to cookie
- [x] if checkbox is checked, save the wage to cookie [overwrite]
- [x] if wage cookie exists, prefill the form and check the checkbox
- [x] if the checkbox is unchecked, clear the cookie value
